# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc856f836e2cc5025bb05d1c7416d562d0b0183f5a8e83ebbd0d10006b093ae064f269ff9d3efecb55c8f766d20b52294e83cd508c28edc39011802d233a9386

test:
  secret_key_base: 68bd5ff8028374d88814be8cd65566b2ff331d295d972deef4ab49d1b03c505857429c9e96aa71077e2f72a16d488add8de55572533c3d7c83a2363cd2d24e8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
